wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight: 
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    columns: [45, 35, 35, 35, 30]
    rows: [7, 9, 11, 11]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    spotify:
      title: " Spotify"
      enabled: true
      colors:
        label: "green"
        text: "white"
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 0
    resourceusage:
      title: "🎛"
      cpuCombined: true
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
    timezones:
      title: "🕖"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        "  GMT": "Etc/GMT"
        🇺🇸USE: "America/New_York"
        🇺🇸USW: "America/Los_Angeles"
        🇹🇼TW: "Asia/Taipei"
      position:
        top: 0
        left: 3
        height: 1
        width: 1
      refreshInterval: 30
      sort: "chronological"
    battery:
      type: power
      title: "⚡️"
      enabled: true
      position:
        top: 0
        left: 4
        height: 1
        width: 1
      refreshInterval: 15
    prettyweather:
      title: "⛅️"
      enabled: true
      city: "New Haven"
      position:
        top: 1
        left: 3
        height: 1
        width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
    security_info:
      type: security
      title: "🌎"
      enabled: true
      position:
        top: 1
        left: 4
        height: 1
        width: 1
      refreshInterval: 3600
    todolist:
      title: "📝 Todo"
      type: todo
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      focusable: true
      filename: "todo.yml"
      position:
        top: 1
        left: 1
        height: 1
        width: 2
      refreshInterval: 3600
    hackernews:
      enabled: true
      numberOfStories: 20
      position:
        top: 2
        left: 1
        height: 1
        width: 2
      storyType: top
      refreshInterval: 3600
    # Work
    jira:
      title: " Jira"
      # apiKey: "" # use $WTF_JIRA_API_KEY in ~/.secrets
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      domain: "https://withpersona.atlassian.net"
      email: "tim@withpersona.com"
      enabled: true
      jql: "status in (Blocked, \"In Progress\", \"In Review\", \"To Do\") AND assignee in (currentUser()) ORDER BY status ASC, lastViewed DESC"
      position:
        top: 2
        left: 3
        height: 1
        width: 2
      project: ["Persona"]
      refreshInterval: 900
      username: "tim"
      verifyServerCertificate: true
    docker:
      title: "🐳 Docker"
      type: docker
      enabled: true
      focusable: true
      labelColor: lightblue
      position:
        top: 0
        left: 0
        height: 3
        width: 1
      refreshInterval: 30
    docker-logs:
      title: "persona-web logs"
      type: cmdrunner
      cmd: "docker-compose-persona-web"
      args: [""]
      enabled: true
      tail: true
      position:
        top: 3
        left: 0
        height: 1
        width: 5
      refreshInterval: 1
